services:
  php:
    build:
      context: .
    volumes:
      - ./php.ini:/etc/php/8.2/cli/conf.d/custom.ini

  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
        - ./src:/var/www/html:delegated
    depends_on:
      - db
      - mailhog
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=biblioteca
      - DB_USERNAME=senai
      - DB_PASSWORD=12345678

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: senai
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: [ "composer" ]

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: [ "php", "artisan" ]

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
